# Generated by Django 6.0 on 2025-12-28 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bandit Messages',
                'db_table': 'banditmessages',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The unique name for the trigger (e.g., 'hrj', 'fj', 'tradingview').", max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Signal Trigger',
                'verbose_name_plural': 'Signal Triggers',
                'db_table': 'signal_triggers',
            },
        ),
        migrations.CreateModel(
            name='SupportedExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Supported Exchanges',
                'db_table': 'supported_exchanges',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_trigger', models.ForeignKey(blank=True, help_text="Link to the source that triggers this strategy's signals.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.signaltrigger')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=40, null=True)),
                ('orderType', models.CharField(blank=True, max_length=255, null=True)),
                ('tpPrice', models.CharField(blank=True, max_length=40, null=True)),
                ('tpStopType', models.CharField(blank=True, max_length=255, null=True)),
                ('tpOrderType', models.CharField(blank=True, max_length=255, null=True)),
                ('tpOrderPrice', models.CharField(blank=True, max_length=40, null=True)),
                ('slPrice', models.CharField(blank=True, max_length=40, null=True)),
                ('slStopType', models.CharField(blank=True, max_length=255, null=True)),
                ('slOrderType', models.CharField(blank=True, max_length=255, null=True)),
                ('tradeSide', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(blank=True, db_column='strategy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
            ],
            options={
                'verbose_name': 'TradingView Signal',
                'db_table': 'signal',
            },
        ),
        migrations.CreateModel(
            name='HRJDiscordSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=255)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('leverage', models.IntegerField(default=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('entry_order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=6)),
                ('stop_loss', models.DecimalField(decimal_places=10, max_digits=20)),
                ('strategy', models.ForeignKey(blank=True, db_column='strategy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
            ],
            options={
                'verbose_name': 'HRJ Discord Signal',
                'db_table': 'hrj_discord_signal',
            },
        ),
        migrations.CreateModel(
            name='FJDiscordSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=255)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('entry_order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=6)),
                ('stop_loss', models.DecimalField(decimal_places=10, max_digits=20)),
                ('strategy', models.ForeignKey(blank=True, db_column='strategy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
            ],
            options={
                'verbose_name': 'FJ Discord Signal',
                'db_table': 'fj_discord_signal',
            },
        ),
        migrations.CreateModel(
            name='UserApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, null=True)),
                ('api_secret', models.CharField(max_length=255, null=True)),
                ('auth_user', models.ForeignKey(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(blank=True, db_column='exchange_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supportedexchange')),
            ],
            options={
                'verbose_name': 'User API Credential',
                'db_table': 'user_api',
            },
        ),
        migrations.CreateModel(
            name='StrategySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=10, null=True)),
                ('leverage_amount', models.IntegerField(blank=True, null=True)),
                ('max_tp_trades', models.IntegerField(blank=True, null=True)),
                ('enable_sl_trail', models.BooleanField(default=True)),
                ('enable_sms_confirm', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(db_column='auth_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(db_column='strategy_id', on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
                ('user_api', models.ForeignKey(blank=True, db_column='user_api_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userapi')),
            ],
            options={
                'verbose_name': 'User Strategy Subscription',
                'db_table': 'strategy_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('street1', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_mark_price', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_value', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_qty', models.CharField(blank=True, max_length=20, null=True)),
                ('auth_user', models.ForeignKey(db_column='auth_user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(db_column='signal_id', on_delete=django.db.models.deletion.CASCADE, to='api.signal')),
            ],
            options={
                'db_table': 'user_trades',
            },
        ),
        migrations.CreateModel(
            name='FJTakeProfitTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_num', models.IntegerField()),
                ('tp_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('signal', models.ForeignKey(db_column='signal_id', on_delete=django.db.models.deletion.CASCADE, to='api.fjdiscordsignal')),
            ],
            options={
                'verbose_name': 'FJ Take Profit Trade',
                'db_table': 'fj_take_profit_trade',
                'unique_together': {('signal', 'series_num')},
            },
        ),
        migrations.CreateModel(
            name='HRJTakeProfitTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_num', models.IntegerField(default=1)),
                ('tp_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('signal', models.ForeignKey(db_column='signal_id', on_delete=django.db.models.deletion.CASCADE, to='api.hrjdiscordsignal')),
            ],
            options={
                'verbose_name': 'HRJ Take Profit Trade',
                'db_table': 'hrj_take_profit_trade',
                'unique_together': {('signal', 'series_num')},
            },
        ),
    ]
