# Generated by Django 6.0 on 2026-01-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIGSCANDiscordSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=255)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('entry_order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=6)),
                ('stop_loss', models.DecimalField(decimal_places=10, max_digits=20)),
                ('strategy', models.ForeignKey(blank=True, db_column='strategy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
            ],
            options={
                'verbose_name': 'SIGSCAN Discord Signal',
                'db_table': 'sigscan_discord_signal',
            },
        ),
        migrations.CreateModel(
            name='SIGSCANTakeProfitTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_num', models.IntegerField()),
                ('tp_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('signal', models.ForeignKey(db_column='signal_id', on_delete=django.db.models.deletion.CASCADE, to='api.sigscandiscordsignal')),
            ],
            options={
                'verbose_name': 'SIGSCAN Take Profit Trade',
                'db_table': 'sigscan_take_profit_trade',
                'unique_together': {('signal', 'series_num')},
            },
        ),
    ]
