# Generated by Django 6.0 on 2026-01-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sigscandiscordsignal_sigscantakeprofittrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapi',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
